services:
  - type: web
    name: swpoptrdg-back
    runtime: python
    rootDir: Back
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate && gunicorn config.wsgi --bind 0.0.0.0:$PORT --log-file -"
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: SUPABASE_DB_NAME
        sync: false
      - key: SUPABASE_USER
        sync: false
      - key: SUPABASE_PASSWORD
        sync: false
      - key: SUPABASE_HOST
        sync: false
      - key: SUPABASE_PORT
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
