# Generated by Django 6.0.5 on 2026-05-21 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('identificador_mesa', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(default=4)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('unida', 'Unida'), ('reservada', 'Reservada')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'mesas',
                'ordering': ['identificador_mesa'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.CharField(choices=[('entrada', 'Entrada'), ('segundo', 'Segundo'), ('bebida', 'Bebida'), ('postre', 'Postre')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_cobro'],
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='api.pago')),
            ],
            options={
                'db_table': 'detalle_pago',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('en_cocina', 'En cocina'), ('listo', 'Listo'), ('despachado', 'Despachado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('id_mesa', models.ForeignKey(blank=True, db_column='id_mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='api.mesas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-tiempo_creacion'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.pedido'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='api.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='api.pedido')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reclamo',
                'ordering': ['-tiempo_creacion'],
            },
        ),
    ]
