# Generated by Django 6.0.4 on 2026-06-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mesas_producto_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Boleta',
                'ordering': ['-fecha_cobro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.CharField(max_length=150)),
                ('cantidad_producto', models.IntegerField()),
            ],
            options={
                'db_table': 'detalle_boleta',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_pedido',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_usuario',
        ),
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mesas',
            options={'managed': False, 'ordering': ['identificador_mesa']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'managed': False, 'ordering': ['-tiempo_creacion']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False, 'ordering': ['categoria', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='reclamo',
            options={'managed': False, 'ordering': ['-tiempo_creacion']},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='DetallePago',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
