# Generated by Django 6.0.5 on 2026-09-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_datosfactura_alter_detallepago_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Password', models.CharField(db_column='password', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(db_column='Usuario', max_length=150, unique=True)),
                ('Nombre', models.CharField(blank=True, db_column='Nombre', max_length=150)),
                ('Apellido', models.CharField(blank=True, db_column='Apellido', max_length=150)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=254)),
                ('Activo', models.BooleanField(db_column='Activo', default=True)),
                ('Rol', models.CharField(choices=[('administrador', 'Administrador'), ('mesero', 'Mesero/a'), ('cocinero', 'Cocinero/a'), ('cajero', 'Cajero/a')], db_column='Rol', default='mesero', max_length=20)),
                ('Fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='Fecha_creacion')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatosFactura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('ruc', models.CharField(max_length=11)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='datos_factura', to='api.pago')),
            ],
            options={
                'db_table': 'datos_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id_detalle_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pago', to='api.pago')),
            ],
            options={
                'db_table': 'detalle_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_pedido', models.ForeignKey(db_column='id_pedidos', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='api.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('identificador_mesa', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField(default=4)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('unida', 'Unida'), ('reservada', 'Reservada')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'mesas',
                'ordering': ['identificador_mesa'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_recibido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha_cobro', models.DateTimeField(auto_now_add=True)),
                ('tipo_comprobante', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('ninguno', 'Ninguno')], default='boleta', max_length=20)),
                ('id', models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.usuario')),
                ('id_pedidos', models.ForeignKey(db_column='id_pedidos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='api.pedido')),
            ],
            options={
                'db_table': 'pago',
                'ordering': ['-fecha_cobro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('en_cocina', 'En cocina'), ('listo', 'Listo'), ('despachado', 'Despachado'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado'), ('anulado', 'Anulado')], default='confirmado', max_length=20)),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('tiempo_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('id_mesa', models.ForeignKey(blank=True, db_column='id_mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='api.mesas')),
                ('id_usuario', models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='api.usuario')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['-tiempo_creacion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['categoria', 'nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia')], max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('tiempo_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('id_pedido', models.ForeignKey(blank=True, db_column='id_pedidos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='api.pedido')),
                ('id_usuario', models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamos', to='api.usuario')),
            ],
            options={
                'db_table': 'reclamo',
                'ordering': ['-tiempo_creacion'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='mesas',
            name='mesa_unida_a',
            field=models.ForeignKey(blank=True, db_column='mesa_unida_a', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesas_unidas', to='api.mesas'),
        ),
    ]
